### ISSUE TITLE
VCF issue?

### ISSUE THREAD

**Issue by cnk113** [hxj5/xcltk#9]
Hi I'm running xcltlk baf with the provided vcf but it looks to be failing to parse?
```
(venv) chang@nidus:/media/sdl/chang/jd/GW14_TS$ xcltk baf --label GW14_TS --sam trimmed_Aligned.sortedByCoord.out.bam --barcode pipseeker/filtered_matrix/sensitivity_5/barcodes.tsv --snpvcf ~/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf.gz --region ~/annotate_genes_hg38_update_20230126.txt --outdir xctlk_baf --gmap ~/Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz --eagle ~/Eagle_v2.4.1/eagle --paneldir ~/1000G_hg38/ --ncores 24
[I::pipeline::pipeline_wrapper] xcltk BAF preprocessing starts ...
[I::pipeline::pipeline_wrapper] check args ...
[I::pipeline::pipeline_wrapper] run in 'droplet' mode (genome version 'hg38')
[I::pipeline::pipeline_wrapper] start pileup ...
[I::pipeline::pipeline_wrapper] pileup VCF is 'xctlk_baf/pileup/cellSNP.base.vcf.gz'.
[I::pipeline::pipeline_wrapper] prepare VCF files for phasing ...
[I::pipeline::pipeline_wrapper] add genotypes ...
Traceback (most recent call last):
  File "/home/chang/miniconda3/envs/venv/bin/xcltk", line 8, in <module>
    sys.exit(main())
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/xcltk/xcltk.py", line 49, in main
    elif command == "baf": baf_baf(sys.argv)
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/xcltk/baf/pipeline.py", line 118, in pipeline_main
    ret = pipeline_wrapper(
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/xcltk/baf/pipeline.py", line 234, in pipeline_wrapper
    vcf_add_genotype(
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/xcltk/baf/genotype.py", line 365, in vcf_add_genotype
    variants, header = vcf_load(in_fn)
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/xcltk/utils/vcf.py", line 62, in vcf_load
    variants = pd.read_csv(fn, sep = "\t", header = None, comment = "#",
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by hxj5** [comment]
Hi, it seems the VCF file of pileup SNP, "xctlk_baf/pileup/cellSNP.base.vcf.gz", is empty. You may check the VCF file. If it is indeed empty, please refer to a related question (in cellsnp-lite) to update the xcltk command-line and inputs accordingly: [Why the output files are empty, no SNPs genotyped?](https://cellsnp-lite.readthedocs.io/en/latest/main/FAQ.html#why-the-output-files-are-empty-no-snps-genotyped)

**Comment by hxj5** [comment]
Hi, sorry for the misleading. I mean you may check the file `xctlk_baf/pileup/cellSNP.base.vcf.gz` (which is also a VCF file), whether it is empty. If empty, you may check and update the command-line arguments and inputs based on the question [Why the output files are empty, no SNPs genotyped?](https://cellsnp-lite.readthedocs.io/en/latest/main/FAQ.html#why-the-output-files-are-empty-no-snps-genotyped)

**Comment by jklvrt** [comment]
hi @hxj5 I am having this exact same issue now. checked that the vcf and BAM files have inconsistent chromosome annotations, and modified the vcf accordingly. still same error. 

more context: sequencing was done with FLASH-seq, and I manually added the 10x style CB:Z tag into the read (now running droplet mode with umitag None). what could be the reason(s)? 

thanks in advance

**Comment by hxj5** [comment]
Hi, you can first check out the FAQ [Why the output files are empty, no SNPs genotyped?](https://cellsnp-lite.readthedocs.io/en/latest/main/FAQ.html#why-the-output-files-are-empty-no-snps-genotyped) If every item listed is fine, you can share a few BAM records and cell barcodes here, as I am not familiar with the FLASH-seq data format.

**Comment by jklvrt** [comment]
Hi, 
thanks for the response. I have referred to that FAQ page with no success. I am also new to FLASH-seq format, attached a screenshot of one of my BAMs, and another screenshot of the barcode file showing that the strings match.  

FLASHseq is technically plate-based, but I have bam files per batch now (within it containing multiple plates). I have manually added the CB tag as you can see in the BAM.

BAM:
<img width="1386" alt="Image" src="https://github.com/user-attachments/assets/47003d5a-7e37-4749-9a70-efe21623f854" />


BC file:

<img width="1387" alt="Image" src="https://github.com/user-attachments/assets/db6ed063-b77c-4eda-919c-7f6d4c5be73a" />

**Comment by jklvrt** [comment]
thanks for the swift response :) ! attached is the pileup log file output. seems something with config annotation in vcf file but I am completely new to CNV analyses so have no idea what is wrong....  ::: 

[I::main] start time: 2025-02-23 14:48:05
[W::check_args] Max depth set to maximum value (2147483647)
[W::check_args] Max pileup set to maximum value (2147483647)
[I::main] global settings after checking:
	num of input files = 1
	out_dir = /media/jonathan/data1/rocio_2024/test_cna/1_pileup
	is_out_zip = 1, is_genotype = 0
	is_target = 0, num_of_pos = 0
	num_of_barcodes = 334, num_of_samples = 0
	refseq file = (null)
	0 chroms: 
	cell-tag = CB, umi-tag = (null)
	nthreads = 20, tp_max_open = 1024
	mthreads = 20, tp_errno = 0, tp_ntry = 0
	min_count = 20, min_maf = 0.10, double_gl = 0
	min_len = 30, min_mapq = 20
	rflag_filter = 1796, rflag_require = 0
	max_depth = 2147483647, max_pileup = 2147483647, no_orphan = 1
[I::main] loading the VCF file for given SNPs ...
[W::vcf_parse] Contig 'chr1 11008 rs575272151 C G 100 PASS AF=0.0880591' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::bcf_hrec_check] Invalid contig name: "chr1 11008 rs575272151 C G 100 PASS AF=0.0880591"
[E::get_snplist_from_vcf] error when parsing '/home/jonathan/DATA2/home/jonathan/miniconda3/envs/xcltk/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.chr.vcf.gz'
[E::main] get SNP list from '/home/jonathan/DATA2/home/jonathan/miniconda3/envs/xcltk/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.chr.vcf.gz' failed.
[E::main] Quiting...
[I::main] Version: 1.2.3 (htslib 1.21)
[I::main] CMD: cellsnp-lite -s /media/jonathan/data1/rocio_2024/transfer_2905338_files_3ae951bd/I23-1431-1434-1435/star/body/Aligned.sortedByCoord.out.modified.bam -b /media/jonathan/data1/rocio_2024/transfer_2905338_files_3ae951bd/I23-1431-1434-1435/star/body/Solo.out/Gene/filtered/barcodes.tsv -O /media/jonathan/data1/rocio_2024/test_cna/1_pileup -R /home/jonathan/DATA2/home/jonathan/miniconda3/envs/xcltk/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.chr.vcf.gz -p 20 --minCOUNT 20 --minMAF 0.1 --cellTAG CB --UMItag None --gzip

**Comment by jklvrt** [comment]
never mind.... managed to solve it by using the original vcf (I artificially added 'chr' which messed up indexing).... now the BAF module works :)
